-- create the raw data tables

CREATE TABLE MY_TABLE (
	MY_ID RAW(16) NOT NULL PRIMARY KEY,
	FREQ_DATE DATE NOT NULL,
	EFFORT NUMBER(10,0) NOT NULL,
	DEFECTS NUMBER(10,0) NOT NULL,
	INSERT_DATE DATE DEFAULT SYSDATE NOT NULL,
	UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);
